language: rust
rust:
  - stable
os:
  - linux
  - osx
dist: trusty
cache: cargo
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh scripts/travis/setup-linux.sh; fi
script:
  - cargo build --tests

