language: rust
rust:
  - stable
os:
  - linux
  - osx
cache: cargo
before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake xorg-dev libglu1-mesa-dev
script:
  - cargo build --tests

