language: rust
rust:
  - stable
os:
  - linux
  - osx
cache: cargo
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; sh scripts/travis/linux.sh; fi
  - if [ $TRAVIS_OS_NAME = mac ]; sh scripts/travis/osx.sh; fi
script:
  - cargo build --tests

