[package]
name = "rust-pushrod"
version = "0.1.1"
authors = ["Ken Suenobu <ksuenobu@fastmail.com>"]
edition = "2018"

[lib]
name = "pushrod"
path = "./src/lib.rs"

[dependencies]
piston_window = "0.87.0"
piston2d-opengl_graphics = "0.59.0"
gfx_core = "0.8.3"
gfx_device_gl = "0.15.5"

[[bin]]
name = "window_test"
path = "src/window_test.rs"
