[package]
name = "rust-pushrod"
version = "0.1.1"
authors = ["Ken Suenobu <ksuenobu@fastmail.com>"]
edition = "2018"
description = "Rust Pushrod GUI Library"
license = "Apache-2.0"
license-file = "LICENSE"
repository = "https://www.github.com/KenSuenobu/rust-pushrod/"
include = [
    "**/*.rs",
    "Cargo.toml",
]
exclude = [
    "src/window_test.rs",
]

[lib]
name = "pushrod"
path = "./src/lib.rs"

[dependencies]
piston_window = "0.87.0"
piston2d-opengl_graphics = "0.59.0"
gfx_core = "0.8.3"
gfx_device_gl = "0.15.5"

[[bin]]
name = "window_test"
path = "src/window_test.rs"
