[package]
name = "rust-pushrod"
version = "0.0.1"
authors = ["Ken Suenobu <ksuenobu@fastmail.com>"]
edition = "2018"

[lib]
name = "pushrod"
path = "./src/lib.rs"

[dependencies]
piston_window = "0.80.0"
